version: 0.2

env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project

phases:
  install:
    runtime-versions:
      nodejs: '20'
    commands:
      - npm install  # Installs dependencies (including sonarqube-scanner)

  build:
    commands:
      - npm test
      - npm run build  # Assuming your build command is 'npm run build'
      - sonar-scanner \
          -Dsonar.login=$LOGIN \
          -Dsonar.host.url=$HOST \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization \
          -Dsonar.sources=. \
          -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js \
          -Dsonar.tests=. \
          -Dsonar.test.inclusions=**/*.test.js,**/*.spec.js







