version: 0.2
env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project
phases:
  install:  # No changes needed here if you already have an install phase
    runtime-versions:  # This section specifies the runtime versions
      nodejs: 20
      java: corretto11  # This line adds Java 11 runtime
  pre_build:  # Rest of your pre-build commands remain here
    commands:
      - yum update -y  # Update package lists
      - yum install -y jq unzip
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - sudo mkdir -p /opt/sonar-scanner
      - mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner/sonar-scanner
      - chmod +x /opt/sonar-scanner/sonar-scanner/bin/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/sonar-scanner/bin
  build:  # Rest of your build commands remain here
    commands:
      - npm install
      - npm run build
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ]; then exit 1; fi













