version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Specify the Node.js version you want to use
    commands:
      - npm install  # Install dependencies
  build:
    commands:
      - npm run build  # Execute the build script
      # Add additional commands for testing if needed
  post_build:
    commands:
      # Add commands for post-build actions such as generating reports or deploying artifacts
      # Example: npm test -- --coverage
      # Example: aws s3 cp dist/ s3://your-bucket-name --recursive
artifacts:
  files:
    # Define the files or directories to be packaged as artifacts
    - '**/*'
























