version: 0.2

phases:
  install:
    commands:
      - echo "Installing npm..."
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -s -- -o /etc/apt/sources.list.d/nodesource.list
      - apt-get update
      - apt-get install -y nodejs
      - echo "Downloading SonarScanner..."
      - SONAR_SCANNER_VERSION=4.7.0.2747  # Set desired version here
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip \
        "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip"
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - echo "Adding SonarScanner to PATH..."
      - export PATH=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux/bin:$PATH

  build:
    commands:
      - echo "Installing project dependencies..."
      # Assuming the project files are already in the working directory (no 'cd')
      - npm install

  post_build:
    commands:
      - echo "Retrieving SonarQube token..."
      - SONARQUBE_TOKEN=$(aws secretsmanager get-secret-value --secret-id local/sonar --query SecretString --output text)
      - echo "Performing SonarQube analysis..."
      sonar-scanner \
          -Dsonar.projectKey=sampletestproject \
          # Assuming the project files are already in the working directory (no 'cd')
          -Dsonar.sources=. \
          -Dsonar.host.url=http://18.139.177.99:9000 \
          -Dsonar.login=$SONARQUBE_TOKEN














