version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - npm test -- --reporters=default --reporters=jest-junit

  post_build:
    commands:
      - mkdir -p reports
      - mv junit.xml reports/

artifacts:
  files:
    - '**/*'
    - 'reports/*'

























