version: 0.2

env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project

phases:
  install:
    runtime-versions:
      nodejs: '20'
    commands:
      - npm install  # Installs dependencies (including sonarqube-scanner)

  build:
    commands:
      # Replace with your specific build command (e.g., for create-react-app)
      - npm run build
      # OR (if using a custom build configuration)
      # Your custom build commands here
      - # SonarQube analysis (assuming downloaded scanner in /opt/sonar-scanner/bin)
      - sonar-scanner \
          -Dsonar.login=$LOGIN \
          -Dsonar.host.url=$HOST \
          -Dsonar.projectKey=$Project \
          -Dsonar.organization=$Organization

  # Optional phases (add if needed)
  # post_build:
  #   commands:
  #     - # Any commands to run after the build is successful









