version: 0.2
env:
  secrets-manager:
    LOGIN: local/sonar:sonartoken
    HOST: local/sonar:HOST
    Organization: local/sonar:Organization
    Project: local/sonar:Project

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - curl -sL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/latest | tar -zxvf -  # Download latest version
      - export PATH=$PATH:/opt/sonar/scanner/bin  # Assuming scanner installed in /opt/sonar

  build:
    commands:
      - npm install
      - npm test
      - npm run build
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
